#! /usr/bin/env python2
"""Un-DEFLATEs the given file (or stdout if not given)

Usage:
    inflate [-h|--help] [--repr] [OBJECT]

With the --repr option, prints the result as a Python string (useful for
binary data)
"""

import zlib
import sys

import docopt

opts = docopt.docopt(__doc__)

if opts['OBJECT']:
    with open(opts['OBJECT']) as file:
        string = file.read()
else:
    string = sys.stdin.read()

if opts['--repr']:
    print repr(zlib.decompress(string))
else:
    sys.stdout.write(zlib.decompress(string))
