#! /usr/bin/env python
"""Un-DEFLATEs the given file (or stdout if not given)

With the --repr option, prints the result as a Python string (useful for
binary data)
"""

import zlib
import sys

# TODO: use docopt
do_repr = '--repr' in sys.argv
if do_repr:
    sys.argv.remove('--repr')

try:
    filename = sys.argv[1]
except IndexError:
    string = sys.stdin.read()
else:
    string = open(filename).read()

if do_repr:
    print repr(zlib.decompress(string))
else:
    sys.stdout.write(zlib.decompress(string))
